### ISSUE TITLE
Erreur potentielle dans les genres des restaurants

### ISSUE THREAD

**Issue by olivierbeausejour** [GLO3102/UFood#22]
Salut!

Je ne sais pas si c'est une erreur, ou si c'est déjà connu, mais dans l'API, il semble avoir 2 catégories de Happy Hour différentes pour les genres de restaurants. Il y a "happy hour" et "happy-hour".

Par exemple, l'URL https://ufoodapi.herokuapp.com/unsecure/restaurants?genres=happy-hour retourne 4 restaurants et l'URL https://ufoodapi.herokuapp.com/unsecure/restaurants?genres=happy%20hour (avec un espace à la place du tiret) en retourne 9 différents.

Je viens de voir aussi qu'il y a un genre "Indienne" et une autre "indien".

Est-ce normal? Car cela peut causer problème pour les requêtes servant de filtrer les restaurants sur la page d'accueil.

Merci :)

Olivier

**Comment by vseguin** [comment]
@ecfy data error?

**Comment by ecfy** [comment]
Ouais typo dans les genres - j'ai corrigé "happy-hour" pour qu'ils apparaissent sous "happy hour". Par contre je ne vois aucun restaurant avec le genre "indienne". @olivierbeausejour Peux-tu revérifier et possiblement nous donner le nom du restaurant pour que je fasse l'ajustement?

**Comment by olivierbeausejour** [comment]
@ecfy 
My bad! Indienne c'était un titre de resto, j'ai mal lu ;)
Merci beaucoup!

**Comment by olivierbeausejour** [comment]
Tant qu'à être ici, je viens de spotter un restaurant qui n'a pas d'attribut price_range. C'est le restaurant avec le nom "Euro-Deli Batory" (https://ufoodapi.herokuapp.com/unsecure/restaurants&q=Euro-Deli%20Batory). Est-ce que c'est normal?

**Comment by ecfy** [comment]
Je viens d'y ajouter un price_range pour ce resto - merci!

**Comment by olivierbeausejour** [comment]
Yessir merci beaucoup! :)
