### ISSUE TITLE
Problème potentiel avec les query params pour le GET restaurants

### ISSUE THREAD

**Issue by JeremieBeaudoin** [GLO3102/UFood#23]
## Contexte
Le fait de spécifier toutes les valeurs possibles pour le price_range ne renvoie pas le même résultat que de ne pas les spécifier tout court. Est-ce que c'est bel et bien des valeurs entre 0 et 5? Je croyais que ma logique client side faisait défaut parce que certains tags ne me renvoyaient pas de resto, mais je suis retourné jouer avec Postman et je me demande si ce comportement est normal ou encore si c'est moi qui fait erreur ailleurs. Je vous joins des captures d'écran ci-bas pour mieux expliquer ce dont je parle.

Lorsque notre application launch, on fait un GET sur tous les restaurants et on stocke tous les tags (du moins ceux que j'arrive à extraire) dans une Map locale. Pour les mises à jour subséquentes du home avec le filtering, on fait un nouveau GET avec des query params pour chaque nouvelle action de l'utilisateur avec les filtres. Je me retrouve donc avec des boutons de filtres qui sont créés (parce que le tag existait dans le GET général initial), mais qui ne renvoient aucun match lors d'un second GET.

**Comment by JeremieBeaudoin** [comment]
J'ai pas pensé aller voir si quelqu'un avait déjà bring up cet issue. Je viens de voir celui soumis par Olivier. Ça semble bel et bien être l'absence de `price_range` dans certains restos qui me donnait du fil à retordre. J'ai fait le tour et voici la liste des restos qui n'ont pas cette info.

```
A La Japonaise
A Pizza Sherbrooke
Antidote FoodLab
Bouffe Dave Plant Food
Boulangerie AMOOL
cafe Restaurant L
Cantine 75
caribbean food factory
Casse Croûte - Kiosque Pouliot St-Laurent
Central Sweets & Food-Hub
Cuisine D'Hélène
Diner Saint-Sauveur
Don Vegan Restaurant - 100% Vegan et   Vegetarian -
Else's
Food De Toi
La Buvette du Centro
Manchu Wok
Marathon Souvlaki Express
Mi Corazon Food Truck
Muffin Plus
Restaurant Au Pot Au Feu Pizza
Restaurant Chez Charlie
Restaurant Le Tpe Food
Tartar Station
Teriyaki Experience
V.S.O.P. Bar
Yakimono Mehadrin Express
```

J'en profite aussi pour mentionner que les restos suivants n'ont pas de genre.
 ```
Schwartz's Deli -   Sandwiches - Steaks
Restaurant Persépolis
caribbean food factory
Mirazu
Cuisine D'Hélène
```

Et finalement, est-ce que je peux vous demander de quelle façon les ratings sont arrondis dans l'api pour le filtering des résultats. Je réalise que notre `Math.round(rating)` pour la conversion du price range en `$` est incompatible avec ce que le serveur renvoie.

Merci!

**Comment by vseguin** [comment]
@ecfy do you have 5 minutes to check this

**Comment by ecfy** [comment]
@vseguin Yep looking into it

**Comment by ecfy** [comment]
Le price_range dans la base de données sont des valeurs de 1 à 5, inclusivement. Je vais regarder si c'est indiqué 0 à 5 quelque part et faire l'ajustement au besoin!

J'ai aussi ajouté le range de prix et les genres sur les restaurants qui n'en avaient pas. Cependant, il s'agit d'un scénario très réaliste que d'avoir certains champs manquants à travers les données - la preuve, ces données viennent directement de Google Places (et j'ai complété les trous avec des données semi-aléatoires). On aurait donc très bien pu demander à l'application de devoir supporter ces cas!
