### ISSUE TITLE
Problème lors de la création d'une visite

### ISSUE THREAD

**Issue by florianfmmartin** [GLO3102/UFood#24]
Bonjour,

J'essaie d'ajouter une visite à un user et je reçois un 404 USER NOT FOUND.

Cepandant :
- Faire un GET à la même adresse me retourne une liste vide, comme quoi le user est présent.
- Faire une requête sans rating me retourne le BAD_REQUEST de [ce fichier](https://github.com/GLO3102/UFood/blob/2941b7ee45c11172621e6baefaf27d47d67d9712/services/visits.js#L129)
- Faire une requête avec un resto invalide me retourne un USER NOT FOUND, comme quoi l'interpréteur ne se rend pas à la ligne 137 du même fichier

J'espère vous avoir donner assez de détail pour que vous puissiez corriger cela.

**Comment by florianfmmartin** [comment]
Il semblerait que le id du resto de ma requête était invalide. Cependant l'erreur retourné par l'API est tout de même incorrecte.

**Comment by vseguin** [comment]
@ecfy if you have 2 seconds there as well
