### ISSUE TITLE
ACCESS_DENIED sur le GET /tokenInfo

### ISSUE THREAD

**Issue by Utar94** [GLO3102/UFood#26]
L'appel **GET /tokenInfo** retourne l'erreur suivante :
`{
    "errorCode": "ACCESS_DENIED",
    "message": "Error retrieving user associated with token"
}`

### Étapes pour reproduire
Effectuer un appel **GET /tokenInfo** en passant l'entête **Authorization** en utilisant un jeton d'authentification valide

### Comportement attendu
Recevoir un objet valide tel décrit dans la documentation de la requête.
https://github.com/GLO3102/UFood/wiki/API:-Token-info

**Comment by Utar94** [comment]
En regardant le code source, j'ai trouvé. Dans le code source suivant, l'entête **Authorization** est utilisée...

![src](https://user-images.githubusercontent.com/9968137/113066419-7e91db80-9188-11eb-99e1-17a614f58bee.png)

... donc de passer l'entête manuellement dans Postman fonctionne, comme sur l'image suivante...

![header](https://user-images.githubusercontent.com/9968137/113066468-91a4ab80-9188-11eb-9823-4849eee21226.png)

... mais d'utiliser l'Authorization built-in dans Postman ne fonctionne pas car l'entête ressemble à `Bearer {token}` :

![bearer](https://user-images.githubusercontent.com/9968137/113066584-c44ea400-9188-11eb-80cc-64fe4ebd3bd0.png)

**Comment by ecfy** [comment]
Bien vu - petite erreur de frappe. Pour l'instant utilises l'en-tête manuelle (tu peux aussi utiliser le paramètre `?access_token=TOKEN` dans l'URL), nous ferons la correction très bientôt.

**Comment by vseguin** [comment]
Issue fixed.
