### ISSUE TITLE
Comportement étrange lors de la déconnexion

### ISSUE THREAD

**Issue by Utar94** [GLO3102/UFood#27]
L'appel de déconnexion retourne `200 OK` lorsque effectué sans jeton d'authentification.

### Étapes pour reproduire
Exécuter l'appel **POST /logout** sans spécifier l'entête **Authorization**

### Comportement attendu
Je devrais recevoir une réponse de `401 Unauthorized`.

**Comment by ecfy** [comment]
Curieux de savoir - pourrais-tu donner un exemple où le 200 engendre un problème qui serait corrigé par une réponse de 401?

Il s'agit évidemment d'un cas très _unusual_, pour lequel il ne semble pas y avoir vraiment de standard - on peut donc juger qu'il s'agit d'une décision d'implémentation plutôt qu'une erreur que de retourner le 200, puisque selon la perspective ça pourrait être considéré comme une requête valide.

Comme il s'agit d'un comportement qui ne brise rien, j'aurais envie de laisser comme ça - si tu y vois problème, laisses-moi savoir et on pourra faire l'ajustement!

**Comment by Utar94** [comment]
@ecfy T'as 100% raison, au final ça reste une décision de design de votre part, tu peux certainement laisser ça comme ça!

J'ai l'habitude que tu doives être connecté à un service afin de te déconnecter, et donc quand j'ai vu le fonctionnement actuel j'ai tout de suite pensé à un bug ou un oubli.

**Comment by vseguin** [comment]
Thanks guys for both reporting and looking :)
