### ISSUE TITLE
Coordonnées extrêmes causent une erreur 500

### ISSUE THREAD

**Issue by olivierbeausejour** [GLO3102/UFood#28]
Bonjour! @ecfy 
Un peu extrême comme bug, mais en implémentant la carte dans le projet de session, je testais lorsque j'allais à des coordonnées extrêmes, genre en Chine ou en Antarctique, et ça a sorti une erreur de serveur.
Ça arrive surtout sur les rebords de la carte, soit au Pôle Nord ou en Antarctique. J'utilise Leaflet comme carte. Faudrait-il que je vérifie les données avant de les envoyer en requête? Ou c'est vraiment une erreur du côté serveur?

Les coordonnées sont dans la console avec l'erreur 500.

![image](https://user-images.githubusercontent.com/78088449/113797782-eebbd680-971f-11eb-9a49-1c528ef56acd.png)

**Comment by ecfy** [comment]
@vseguin Pourrais-tu vérifier les logs quand tu auras 2 minutes? Pas certain de comprendre pourquoi ces coordonnées causeraient problème plus que d'autres seulement qu'en regardant le code.
