### ISSUE TITLE
Mauvais message d'erreur ou route unsecure pas fonctionnelle

### ISSUE THREAD

**Issue by NicolasChoquet** [GLO3102/UFood#29]
GET: https://ufoodapi.herokuapp.com/unsecure/users/615a11f2bf1a1700041d0421
Retourne: 
{
    "id": "615a11f2bf1a1700041d0421",
    "name": "Jeff EQ6",
    "email": "jeff.eq6@domain.com",
    "rating": 0,
    "following": [],
    "followers": []
}

et 

POST: https://ufoodapi.herokuapp.com/unsecure/users/615a11f2bf1a1700041d0421/restaurants/visits
Retourne:
{
    "errorCode": "USER_NOT_FOUND",
    "message": "User 615a11f2bf1a1700041d0421 was not found"
}

Normalement l'erreur devrait être: Il faut le token pour continuer, mais là l'erreur n'est pas représentative de la situation

**Comment by vseguin** [comment]
@NicolasChoquet ` Il faut le token pour continuer, mais là l'erreur n'est pas représentative de la situation` - tu utilises l'api unsecure, donc je ne suis pas sur de comprendre pourquoi tu expectes ce message?

**Comment by NicolasChoquet** [comment]
Parce que le message retourné n'est pas représentatif? L'erreur n'étais pas que l'utilisateur n'existait pas mais que je n'étais pas connecté.
Si la route requiert une authentification et que la requête est pas authentifié, alors le premier retour de l'app devrait dire qu'il faut être authentifié.

**Comment by vseguin** [comment]
Mais la route n'a pas besoin d'etre authentifiee, _normalement_. Il semble y avoir un probleme - mais pas ce qui est decrit ici.

**Comment by NicolasChoquet** [comment]
Dans la documentation oui il est écrit quil faut être authentifié

**Comment by vseguin** [comment]
Oui evidemment, pour la route secure. La route unsecure ne le demande pas (comme toutes les autres routes unsecure).

**Comment by NicolasChoquet** [comment]
Alors il faut utiliser la route unsecure ou secure? 
La doc dit qu'il faut absolument utiliser un token, mais vous avez l'air de dire qu'il faut utiliser la unsecure, mais comme j'ai démontré avec le premier message, elle ne marche pas.

**Comment by vseguin** [comment]
> Alors il faut utiliser la route unsecure ou secure? La doc dit qu'il faut absolument utiliser un token, mais vous avez l'air de dire qu'il faut utiliser la unsecure, mais comme j'ai démontré avec le premier message, elle ne marche pas.

Pour le livrable 2, vous devriez toujours utiliser les routes unsecure, a moins que vous ayez deja le login d'implemente?

J'aimerais avoir la requete complete si possible, notamment avec les headers. Ceci dit, je suis surpris que la route ne fonctionne pas 🤔

**Comment by vseguin** [comment]
![image](https://user-images.githubusercontent.com/1884896/135773758-bcfdadfd-a840-4cf5-96d1-61ba8ee98957.png)

Je confirme que la route fonctionne bien. 

Voici mon curl:
```
curl --location --request POST 'https://ufoodapi.herokuapp.com/unsecure/users/615a11f2bf1a1700041d0421/restaurants/visits' \
--header 'Accept: */*' \
--header 'Content-Type: application/json' \
--data-raw '{
    "restaurant_id": "5f31fc6155d7790550c08afe",
    "rating": 5
}'
```

Peut-etre le application/json qui manque?

Dans tous les cas, ca semble etre un probleme dans ton code/facon d'appeller la route.

**Comment by NicolasChoquet** [comment]
Voici ma requête postman et ce quelle retourne 
![Capture](https://user-images.githubusercontent.com/60526173/135773966-71c98311-9313-4928-9b75-ab926001c3f2.PNG)

Voici les headers
![image](https://user-images.githubusercontent.com/60526173/135773971-6b39b164-09ab-412f-94bd-8ad04946eb80.png)

**Comment by NicolasChoquet** [comment]
Voici ce qui prouve que l'utilisateur existe bien:
![image](https://user-images.githubusercontent.com/60526173/135773989-027ae73f-bb82-472e-b4ba-56a63cb3517c.png)

Si vous voulez essayer, voici l'id de l'utilisateur: 615a11f2bf1a1700041d0421

**Comment by vseguin** [comment]
![image](https://user-images.githubusercontent.com/1884896/135774050-209e8a6b-5217-4f4b-a064-76e33ccc5790.png)

Pas sur de quoi te dire, mais moi tout fonctionne. Peut tu copier/coller ton curl?

**Comment by NicolasChoquet** [comment]
Trouvé l'erreur, c'est le no de resto
Peut être que régler le message d'erreur aiderais parce que a ce que je vois des autres issues fermés, je ne suis pas le premier et c'est bel et bien un bug

**Comment by vseguin** [comment]
Aha! Je vois l'erreur. Je vais fixer ca, merci de l'issue!
