### ISSUE TITLE
Erreur 500 lors de la création d'une visite, mais la crée pareil

### ISSUE THREAD

**Issue by NicolasChoquet** [GLO3102/UFood#30]
Bonjour, lorsque j'envoye une requête au serveur pour créer une visite, sa me retourne une erreur 500, mais elle est créée quand même. Je reçois seulement un erreur 500 avec un body contenant un objet vide { }. 

Path: https://ufoodapi.herokuapp.com/unsecure/users/615a11f2bf1a1700041d0421/restaurants/visits
Body: {"date":"2021-10-14T06:00:00.000Z","comment":"test","rating":1,"restaurant_id":"5f31fc6555d7790550c08aff"}

Avant les corrections j'ai pu ajouter des visits, alors est-il possible qu'il y ai des données corrompus dans la BD?

**Comment by vseguin** [comment]
Merci, j'ai fixe le probleme!
