### ISSUE TITLE
Erreur 500 lorsqu'on exécute une requête http post pour ajouter une visite à un restaurant

### ISSUE THREAD

**Issue by mountaulaval** [GLO3102/UFood#31]
Lorsque j'essaye de post une visite de restaurant dans l'API ([Comme indiqué ici](https://github.com/GLO3102/UFood/wiki/API:-Visites-de-restaurant#post-usersidrestaurantsvisits)), celui-ci me retourne une erreur 500:

![image](https://user-images.githubusercontent.com/80405490/139706069-bea0cd33-f991-44af-8e00-96519d0661dc.png)

Le post semble par contre bien s'effectuer car la visite s'affiche par la suite lorsque je fait un get pour obtenir les visites d'un restaurant.

Voici la commande fetch utilisé pour faire l'appel:

`const response = await fetch(
``${API_URL}/users/${userId}/restaurants/visits``,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(data),
      }
    );`

![image](https://user-images.githubusercontent.com/80405490/139706128-4609ee3b-d49b-49ec-b1dd-90ae1190c3df.png)

L'API_URL correspond à l'url de l'api en unsecure (https://ufoodapi.herokuapp.com/unsecure), et le data est l'objet qui est requis pour le body comme spécifié dans la documentation de l'appel POST.

Le data et le userId ne semblent pas être la cause du problème puisque l'ajout de la visite se fait correctement, par contre je pourrai répondre à des questions par rapport à ceux-ci si besoin. 

Merci!

**Comment by vseguin** [comment]
Fixed!
