### ISSUE TITLE
Petites erreurs dans le wiki de l'API

### ISSUE THREAD

**Issue by SilverPh0ton** [GLO3102/UFood#32]
Bonsoir,
Je crois avoir repéré 2 petits inexactitude dans le wiki de l'API
[Cette partie pour être exact](https://github.com/GLO3102/UFood/wiki/API:-Restaurants#get-restaurants)

L'exemple pour filtrer par genre semble inexact. Je crois que ca devrais plutôt être quelque chose comme ca ```/restaurants?genres=ambiance,café```
![image](https://user-images.githubusercontent.com/37762128/151915698-3f40d0f3-b384-4a34-a89c-6182f194b1f9.png)

Sinon, je ne sais pas si c'est une oublie dans le payload retourné ou dans le wiki mais il y a un ```place_id``` dans le payload des restaurants qui n'est pas mentionné dans le wiki. Ca semble être un id pour l'API de Google Map donc ca pourrais être utile à laisser si jamais ce n'étais pas supposé être retourné

C'est des petits détails mais je me suis dit que ca pourrais éviter quelques confusions

**Comment by vseguin** [comment]
Yes je corrige ca! Merci :)
