### ISSUE TITLE
La route /unsecure/follow provoque forcement une erreur 500

### ISSUE THREAD

**Issue by aurelienjoncour** [GLO3102/UFood#46]
Les routes /unsecure/follow et /unsecure/unfollow provoque forcement une erreur 500 car le middleware isAuthenticated n'est pas appelé et donc l'objet req.user est indéfinis.

**Comment by vseguin** [comment]
Il n'est pas possible de follow en unsecure, donc bien possible... surement qu'il faudrait enlever ces routes simplement.
