### ISSUE TITLE
Wiki API

### ISSUE THREAD

**Issue by benji-35** [GLO3102/UFood#53]
Route "[/users/:id/restaurants/:id/visits](https://github.com/GLO3102/UFood/wiki)" ne retourne pas vers la documentation de celle-ci.

**Comment by vseguin** [comment]
Serait-il possible de preciser ce que cette issue veux dire exactement?

**Comment by benji-35** [comment]
Dans la documentation de l'API, il y a la catégorie "Visite de restaurant".
La dernière URL de cette partie (GET /users/{id}/restaurants/{id}/visits), lorsqu'on clique ne retourne pas vers sa documentation.

Benjamin DELVERT
Etudiant 4ème année (PGE)
Epitech Paris
Tel : +33 604523968
Email : ***@***.***
[cid:05f283f2-e534-44ff-b12b-708dc82dfb1d]
________________________________
De : Vincent Seguin ***@***.***>
Envoyé : vendredi 6 octobre 2023 22:40
À : GLO3102/UFood ***@***.***>
Cc : Benjamin DELVERT ***@***.***>; Author ***@***.***>
Objet : Re: [GLO3102/UFood] Wiki API (Issue #53)


Serait-il possible de preciser ce que cette issue veux dire exactement?

**Comment by vseguin** [comment]
Merci, solved!
