### ISSUE TITLE
Une request DELETE sur /unsecure/favorites/:id retourne une erreur 500

### ISSUE THREAD

**Issue by Rayz224** [GLO3102/UFood#54]
Bonjour!
Je reçois une erreur 500 lorsque j'essaye de supprimer une liste de favoris d'un utilisateur avec une request DELETE sur `.../unsecure/favorites/:id`

Erreur dans la console:
![image](https://github.com/GLO3102/UFood/assets/31826346/9d0597ed-8e06-4246-925a-d5c6a6c53157)

Quand j'essaye sur la version local de l'API, l'erreur `TypeError: favoriteList.remove is not a function` est lancée par le serveur:
![image](https://github.com/GLO3102/UFood/assets/31826346/bd4e183e-4862-49f6-a7df-beba4a4c48e6)

**Comment by vseguin** [comment]
Merci, fixed!

**Comment by Rayz224** [comment]
Merci!, la request ne retourne plus d'erreur 500 mais elle ne semble pas supprimer la liste de la base de donnée.

Ici je delete la liste id `65ebb5eed40e5bc7b689347b`.

![image](https://github.com/GLO3102/UFood/assets/31826346/6499b5ea-62b4-4265-b804-fa36887b046a)

Dans la request `GET /unsecure/users/{userID}/favorites` faite juste après, la liste `65ebb5eed40e5bc7b689347b` (Test1) est encore présente.

![image](https://github.com/GLO3102/UFood/assets/31826346/dca06a5f-90a8-47e3-96a4-f78aa3c46ba6)

**Comment by Rayz224** [comment]
La ligne 186 `restaurantToRemove.remove()` devrait aussi être changée.
