### ISSUE TITLE
Suppression d'un restaurant dans une liste de favoris non fonctionnel

### ISSUE THREAD

**Issue by xpelch** [GLO3102/UFood#55]
Lors d'un appel au endpoint `DELETE `/favorites/:id/restaurants/:restaurantId avec les bons paramètre, le restaurant n'est pas supprimé de la liste de favoris.

On retourne la liste tel quel sans effectuer de delete dessus comme démontré via postman:

![image](https://github.com/GLO3102/UFood/assets/77986237/79d379d8-3d3c-4bf0-bd49-c3e74f90c24f)

**Comment by vseguin** [comment]
Fixing as part of https://github.com/GLO3102/UFood/issues/54.
