### ISSUE TITLE
Bug de init pour le login Facebook

### ISSUE THREAD

**Issue by kingmufasa99** [GLO3102/UFood#61]
![image](https://github.com/GLO3102/ufood-h2024-team-05/assets/77929993/0198ca06-d82c-425b-8b81-ea1bce77efea)

Je n'arrête pas d'avoir des problème de init quand je clique sur le login Facebook. Au début j'avais l'erreur "FB.login called before FB.init", puis quand j'ai réussi à réglé le problème, j'ai présentement l'erreur "init not called with valid version".

Toutes mes méthodes pour ce feature sont dans le fichier pages/Login.vue sur la branche User-Login-Externe-TP3
J'ai aussi adapté mon vue.config.js.
Je pense que j'ai importé correctement le Facebooksdk. J'ai aussi activer mon compte Facebook app. J'ai FB.init le appId entre autre (944329650523749).
@vseguin @kingmufasa99 

Voici un extrait de mon code: 
![image](https://github.com/GLO3102/ufood-h2024-team-05/assets/77929993/e9ea3295-efb7-4d42-8388-7067dd13a48a)

**Comment by vseguin** [comment]
This is not related to UFood itself. Closing.
